### ISSUE TITLE
Replace maxflow implementation for licence compatibility purposes

### ISSUE THREAD

**Issue by tvercaut** [masadcv/torchmaxflow#1]
As shown in the current version of this repo, the maxflow implementation is based on v3.04 of Yuri Boykov and Vladimir Kolmogorov code (see https://pub.ist.ac.at/~vnk/software.html):
https://github.com/masadcv/torchmaxflow/tree/eb1feb192dff053890d005c7c396b6dd11f3e7ba/torchmaxflow/maxflow-v3.04.src

The code is licensed under GPL which is incompatible with the permissive licence used in this repo:
https://github.com/masadcv/torchmaxflow/blob/main/LICENSE

Other implementation of the Boykov-Kolmogorov maxflow algorithm exist, e.g. in OpenCV and Boost. These have been wrapped for exmaple here:
https://github.com/luiscarlosgph/grabcut/tree/main/inc/grabcut

**Comment by masadcv** [comment]
This has been resolved. I was able to use OpenCV v2.4 version of graphcut. Since it is also BSD-3 clause license, it is in-line with this library.

**Comment by tvercaut** [comment]
Nice. From what I can see, the code is essentially the same in the latest version of OpenCV:
https://github.com/opencv/opencv/blob/4.x/modules/imgproc/include/opencv2/imgproc/detail/gcgraph.hpp

A diff
https://www.diffnow.com/report/x4ptn
shows that you may only need to add 2 asserts here:
https://github.com/masadcv/torchmaxflow/blob/551aa0915fddb7234b0b1be3a9249df66a6e5644/torchmaxflow/graphcut.h#L167-L170
to be on par with the latest OpenCV:
https://github.com/opencv/opencv/blob/9aa647068b2eba4a34462927b1878353dfd3df69/modules/imgproc/include/opencv2/imgproc/detail/gcgraph.hpp#L155-L160

You can then update your README to reassure people that this is the same as recent OpenCV.

**Comment by masadcv** [comment]
Many thanks for detailed overview of changes required! I somehow missed this path in latest opencv.
All updated now!
