### ISSUE TITLE
[FEATURE] GPU support of torchmaxflow

### ISSUE THREAD

**Issue by vhchuong** [masadcv/torchmaxflow#10]
Hello,

This implementation is important to my field of research. Are there any plans to implement GPU support for this PyTorch version of maxflow?
![image](https://github.com/user-attachments/assets/bf5feba6-7c66-400c-9624-2d4548f57dc8)

Thank you.

**Comment by masadcv** [comment]
Hi, 
Thanks for your interest in this library. 
Unfortunately, the method that is currently implemented is not directly parallelizable on GPU. 
You may find other methods to do graphcut/maxflow on GPU... 
There is also GPU CRF implementation within MONAI: https://gist.github.com/masadcv/84f1bc9f505056ea8f4290d14a002d2a (not sure of the latest status of this)

Good luck with your research! 
Muhammad Asad
